# Generated by Django 6.0.4 on 2026-05-01 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('avatar', models.CharField(max_length=10)),
                ('expertise', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('deals_closed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('tier', models.CharField(choices=[('Probation', 'Probation'), ('Active', 'Active'), ('Trusted', 'Trusted')], default='Probation', max_length=20)),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SaaS', 'SaaS'), ('Fintech', 'Fintech'), ('D2C', 'D2C'), ('Enterprise', 'Enterprise'), ('Marketing', 'Marketing'), ('Consulting', 'Consulting')], max_length=50)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('type', models.CharField(choices=[('Lead', 'Lead'), ('Partnership', 'Partnership'), ('Hiring', 'Hiring'), ('Investment', 'Investment')], max_length=50)),
                ('confidence', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('timeline', models.CharField(max_length=100)),
                ('decision_access', models.CharField(max_length=50)),
                ('budget_clarity', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated'), ('in_progress', 'In Progress'), ('closed', 'Deal Closed'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('claims', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_opportunities', to='core.member')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_opportunities', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.opportunity')),
            ],
        ),
    ]
