# Generated by Django 5.2.13 on 2026-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_password_profile_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='budget_clarity',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Manufacturing', 'Manufacturing'), ('Consulting', 'Consulting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='decision_access',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='timeline',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('Referral', 'Referral'), ('Introduction', 'Introduction'), ('Execution Ready', 'Execution Ready')], max_length=50),
        ),
    ]
