# Generated by Django 5.2.13 on 2026-05-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_channel_opportunity_channel_channelmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_claims', to='core.member')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_claims', to='core.opportunity')),
            ],
            options={
                'unique_together': {('opportunity', 'claimant')},
            },
        ),
    ]
