# Generated by Django 5.2.13 on 2026-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_opportunityclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='claims',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
