# Generated by Django 5.2.13 on 2026-05-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_opportunity_claims_alter_opportunity_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('Fintech', 'Fintech'), ('D2C', 'D2C'), ('Enterprise', 'Enterprise'), ('Marketing', 'Marketing'), ('Consulting', 'Consulting'), ('IT', 'IT'), ('Manufacturing', 'Manufacturing')], max_length=50),
        ),
    ]
