# Generated by Django 5.2.13 on 2026-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_opportunity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tier',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Member', 'Member')], default='Member', max_length=20),
        ),
    ]
