# Generated by Django 5.2.13 on 2026-05-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
