/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubmitRouteImport } from './routes/_app/submit'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile.index'
import { Route as AppProfileIdRouteImport } from './routes/_app/profile.$id'
import { Route as AppOpportunityIdRouteImport } from './routes/_app/opportunity.$id'
import { Route as AppChannelIdRouteImport } from './routes/_app/channel.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubmitRoute = AppSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunityIdRoute = AppOpportunityIdRouteImport.update({
  id: '/opportunity/$id',
  path: '/opportunity/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelIdRoute = AppChannelIdRouteImport.update({
  id: '/channel/$id',
  path: '/channel/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/channels': typeof AppChannelsRoute
  '/feed': typeof AppFeedRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/submit': typeof AppSubmitRoute
  '/channel/$id': typeof AppChannelIdRoute
  '/opportunity/$id': typeof AppOpportunityIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile/': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/channels': typeof AppChannelsRoute
  '/feed': typeof AppFeedRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/login': typeof AppLoginRoute
  '/register': typeof AppRegisterRoute
  '/submit': typeof AppSubmitRoute
  '/channel/$id': typeof AppChannelIdRoute
  '/opportunity/$id': typeof AppOpportunityIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/channels': typeof AppChannelsRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/submit': typeof AppSubmitRoute
  '/_app/channel/$id': typeof AppChannelIdRoute
  '/_app/opportunity/$id': typeof AppOpportunityIdRoute
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/_app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/channels'
    | '/feed'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/submit'
    | '/channel/$id'
    | '/opportunity/$id'
    | '/profile/$id'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/channels'
    | '/feed'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/submit'
    | '/channel/$id'
    | '/opportunity/$id'
    | '/profile/$id'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/channels'
    | '/_app/feed'
    | '/_app/leaderboard'
    | '/_app/login'
    | '/_app/register'
    | '/_app/submit'
    | '/_app/channel/$id'
    | '/_app/opportunity/$id'
    | '/_app/profile/$id'
    | '/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/submit': {
      id: '/_app/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AppSubmitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunity/$id': {
      id: '/_app/opportunity/$id'
      path: '/opportunity/$id'
      fullPath: '/opportunity/$id'
      preLoaderRoute: typeof AppOpportunityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channel/$id': {
      id: '/_app/channel/$id'
      path: '/channel/$id'
      fullPath: '/channel/$id'
      preLoaderRoute: typeof AppChannelIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppSubmitRoute: typeof AppSubmitRoute
  AppChannelIdRoute: typeof AppChannelIdRoute
  AppOpportunityIdRoute: typeof AppOpportunityIdRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppFeedRoute: AppFeedRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppSubmitRoute: AppSubmitRoute,
  AppChannelIdRoute: AppChannelIdRoute,
  AppOpportunityIdRoute: AppOpportunityIdRoute,
  AppProfileIdRoute: AppProfileIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
